import React from 'react';
import { ShieldAlert, Scale, Construction } from 'lucide-react';

const EthicsSection: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto py-16 animate-in fade-in slide-in-from-bottom-10">
            <div className="mb-16">
                <h2 className="text-5xl font-black mb-6 tracking-tighter text-[#001a3d]">Ethics & Disclaimer</h2>
                <p className="text-xl text-slate-500 font-medium leading-relaxed">Commitment to scientific integrity and responsible AI usage.</p>
            </div>

            <div className="space-y-8">
                <div className="bg-amber-50 border border-amber-100 p-10 rounded-[40px] flex gap-8 items-start">
                    <div className="w-16 h-16 bg-amber-500 text-white rounded-2xl flex items-center justify-center shrink-0 shadow-lg">
                        <ShieldAlert size={32} />
                    </div>
                    <div className="space-y-4">
                        <h3 className="text-2xl font-black text-amber-900 tracking-tighter uppercase">AI Generation Warning</h3>
                        <p className="text-amber-800/80 leading-relaxed font-semibold text-base">
                            Orphafold is <strong>NOT a drug discovery tool</strong>. It is a Generative AI interface that aggregates public knowledge and generates hypotheses.
                            <br /><br />
                            The "candidates" proposed are synthetic suggestions based on pattern matching. <strong>AI can hallucinate mechanisms or associations.</strong> All outputs must be rigorously verified against primary literature and experimental validation.
                        </p>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="bg-white border border-slate-100 p-10 rounded-[40px] shadow-sm space-y-6">
                        <div className="w-12 h-12 bg-slate-100 text-[#001a3d] rounded-xl flex items-center justify-center shadow-inner">
                            <Scale size={24} />
                        </div>
                        <h4 className="text-xl font-black text-[#001a3d] tracking-tighter">Human-in-the-loop</h4>
                        <p className="text-slate-500 text-sm leading-relaxed font-medium">
                            This tool is intended to <strong>augment</strong>, not replace, the expertise of medical researchers and geneticists. Scientific discovery remains a human-centric endeavor requiring peer-reviewed verification.
                        </p>
                    </div>

                    <div className="bg-white border border-slate-100 p-10 rounded-[40px] shadow-sm space-y-6">
                        <div className="w-12 h-12 bg-slate-100 text-[#001a3d] rounded-xl flex items-center justify-center shadow-inner">
                            <Construction size={24} />
                        </div>
                        <h4 className="text-xl font-black text-[#001a3d] tracking-tighter">Experimental Status</h4>
                        <p className="text-slate-500 text-sm leading-relaxed font-medium">
                            Data generated by our agent is grounded in live registries but may be subject to Gemini's synthesis errors. Always cross-reference findings with the original source links provided in the report.
                        </p>
                    </div>
                </div>

                <div className="text-center pt-12">
                    <p className="text-[10px] font-black uppercase tracking-[0.5em] text-slate-300">Hackathon Build v0.9.3 - 2025</p>
                </div>
            </div>
        </div>
    );
};

export default EthicsSection;
